#!/usr/bin/env zsh

PATTERNS=('only' 'console\.log');

git stash -q --keep-index

git diff --cached --name-only | while read FILE; do
  if [[ -f $FILE ]]; then
    grep -qE "${(j:|:)PATTERNS}" "$FILE"
    if [ $? -eq 0 ]; then
      grep --color -nE "${(j:|:)PATTERNS}" "$FILE"
      exit 1
    fi
  fi
done || exit $?

npm run test

RESULT=$?

git stash pop -q

exit $RESULT

